import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react"
import Basic from "../components/basic"
import 'bootstrap/dist/css/bootstrap.min.css'


export default function Home() {
  return (
    <div className="container mt-3">
    
        <Head>
          <title>Sign Up</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
      
      <div className = "row">
        <div className ="col-md-5">
           <Basic />
        </div>
        <div className = "col-md-7 my-auto">
        <img className = "img-fluid w-100" src="/rocket.png" alt = "Rocket"/>
        </div>    
      </div>  

    </div>
  )
}
